version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Uncomment and add your Gemini API key if you have one
      # - GEMINI_API_KEY=your_gemini_api_key_here
    networks:
      - pharmaguard-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - pharmaguard-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  pharmaguard-network:
    driver: bridge 